### ISSUE TITLE
1.4版本报错

### ISSUE THREAD

**Issue by joel1022** [aoaostar/toolbox#15]
登录的时候报错显示SQLSTATE[42000]: Syntax error or access violation: 1305 FUNCTION toolbox.json_extract does not exist

**Comment by aoaostar** [comment]
https://github.com/aoaostar/toolbox/blob/77a67bb6d46addfb03b2d3514e3f7ffe234c7211/README.md?plain=1#L28-L31
[docs: ✏️ 修正环境要求](https://github.com/aoaostar/toolbox/commit/618c483b28a3a8aac4fab608dddf10aa0e453650)

**Comment by joel1022** [comment]
我用的是7.4

**Comment by aoaostar** [comment]
> 我用的是7.4

你这是MySQL版本小于5.7了，只有MySQL5.7+才支持json查询
