### ISSUE TITLE
报错

### ISSUE THREAD

**Issue by cycxtIT** [aoaostar/toolbox#2]
报错提示：
Warning: require(/www/wwwroot/tool.cycxtit.eu.org/public/../vendor/autoload.php): failed to open stream: No such file or directory in /www/wwwroot/tool.cycxtit.eu.org/public/index.php on line 14

Fatal error: require(): Failed opening required '/www/wwwroot/tool.cycxtit.eu.org/public/../vendor/autoload.php' (include_path='.:') in /www/wwwroot/tool.cycxtit.eu.org/public/index.php on line 14

**Comment by aoaostar** [comment]
安装依赖

**Comment by cycxtIT** [comment]
> 安装依赖

我用aws搭建的，还需要安装多一次依赖吗

**Comment by cycxtIT** [comment]
> 安装依赖

好的我明天试试

**Comment by cycxtIT** [comment]
> 安装依赖

已经安装了还是一样，防跨站也关了

**Comment by aoaostar** [comment]
依赖安装了，防跨站也关了，看看PHP版本对不对吧

**Comment by cycxtIT** [comment]
> 依赖安装了，防跨站也关了，看看PHP版本对不对吧

php 7.4

**Comment by cycxtIT** [comment]
> 依赖安装了，防跨站也关了，看看PHP版本对不对吧

刚刚看了安装依赖的日志显示problem

**Comment by cycxtIT** [comment]
> 依赖安装了，防跨站也关了，看看PHP版本对不对吧

宝塔是不是出bug了？因为我安装好了fileinfo那提示未安装。。。可以任务列表提示已经安装

**Comment by aoaostar** [comment]
> > 依赖安装了，防跨站也关了，看看PHP版本对不对吧
> 
> 宝塔是不是出bug了？因为我安装好了fileinfo那提示未安装。。。可以任务列表提示已经安装

重启一下PHP吧
