### ISSUE TITLE
安装插件 "连接云中心失败，请检查网络连通性是否正常"

### ISSUE THREAD

**Issue by GryaLeaf** [aoaostar/toolbox#37]
检查服务器的网络都是畅通的，也能正常连github，不知道为啥会有这个提示 "连接云中心失败，请检查网络连通性是否正常"
![_75A`@ZBS3@AYY@1IMM)CHH](https://github.com/aoaostar/toolbox/assets/43517866/f10366eb-b1f9-42bf-a6f1-0d79064c2f38)

**Comment by aoaostar** [comment]
服务器磁盘满了，已经好了
