### ISSUE TITLE
安装成功后，首页怎么空白？

### ISSUE THREAD

**Issue by klmahua** [aoaostar/toolbox#4]
安装成功后，首页怎么空白？默认数据没有吗，。。管理后台也进不去

**Comment by aoaostar** [comment]
域名给一下，啥也不给，怎么排查
很多人都安装成功了，没有理由失败的，好好看看`readme`吧

**Comment by klmahua** [comment]
我这是本地安装，，，要填写的clienid  不知道是什么东西

**Comment by aoaostar** [comment]
> 我这是本地安装，，，要填写的clienid 不知道是什么东西

接入github oauth
https://springboot.io/t/topic/1063
