### ISSUE TITLE
保存系统设置，报错：“服务器错误，请联系管理员”

### ISSUE THREAD

**Issue by tyultra** [aoaostar/toolbox#47]
操作步骤：修改自定义底部代码，点击保存，报错：“服务器错误，请联系管理员”。
浏览器：Chrome
系统：Win11
![image](https://github.com/aoaostar/toolbox/assets/36122504/6a7bb105-0193-4854-8c58-e44ca4dc3515)

**Comment by aoaostar** [comment]
修改自定义底部代码

修改成啥了

**Comment by tyultra** [comment]
> 修改自定义底部代码
> 
> 修改成啥了

增加百度统计和GA的统计代码如下：
<script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=XXXXXXXXXXXXXXXXXXX"crossorigin="anonymous"></script>

<script async src="https://www.googletagmanager.com/gtag/js?id=XXXXXXXXXXX"></script>
<script>
  var _hmt = _hmt || [];
  (function() {
  var hm = document.createElement("script");
  hm.src = "https://hm.baidu.com/hm.js?XXXXXXXXXXXXXXXXXXXXXXXXXXX";
  var s = document.getElementsByTagName("script")[0]; 
  s.parentNode.insertBefore(hm, s);
  })();
</script>

**Comment by aoaostar** [comment]
数据库设计字段短了，得把目标字段改成text

**Comment by tyultra** [comment]
> 数据库设计字段短了，得把目标字段改成text

你们发布新版本修改，还是说我能自行修改？

**Comment by aoaostar** [comment]
自己改一下，已经没空更新了

**Comment by aoaostar** [comment]
toolbox_config表的value字段

**Comment by tyultra** [comment]
> toolbox_config表的value字段

谢谢~
