### ISSUE TITLE
sqlstate 报错

### ISSUE THREAD

**Issue by cycxtIT** [aoaostar/toolbox#6]
请问一下要怎么解决
如图：
![Screenshot_20220303-163747_Chrome](https://user-images.githubusercontent.com/90236905/156531146-91835157-295e-4a8e-898d-648f68195d1e.jpg)

**Comment by aoaostar** [comment]
显而易见，数据库连接失败

**Comment by cycxtIT** [comment]
> 显而易见，数据库连接失败

我也知道可是我都还没安装工具箱

**Comment by cycxtIT** [comment]
> 显而易见，数据库连接失败

我也知道可是我都还没安装工具箱
